### ISSUE TITLE
Cat ref genome issue

### ISSUE THREAD

**Issue by melbarb12** [jonahcullen/wags#31]
Hi Dr. Cullen 
I am trying to prep samples for calling and I cannot seem to call the included cat reference genome. It is not in the references of prep_subs.py. I have run my line for every other reference genome in the built in genome section and samples have been processed, but the cat reference does not work.  Instead of being directed to reference genome it is trying to look at custom genome submission. Any suggestions for this issue?
    assert tmp, f"config not found for {ref}, ensure prep_custom_ref.py ran successfully and check ref_dir"
AssertionError: config not found for cat, ensure prep_custom_ref.py ran successfully and check ref_dir

**Comment by jonahcullen** [comment]
Apologies I failed to update `prep_subs.py` to include the latest cat reference! If you go ahead and pull the latest version of this repo, it should work with `--ref Fca126_mat1.0`. Let me know if you experience any other issues getting it going for your cat samples!

**Comment by melbarb12** [comment]
Thank you, issue was resolved. I look forward to using the pipeline :)
