### ISSUE TITLE
To see all reference genome

### ISSUE THREAD

**Issue by sachin11645** [jonahcullen/wags#32]
skipping mount of /lscratch: stat /lscratch: no such file or directory
FATAL:   container creation failed: mount hook function failure: mount /lscratch->/lscratch error: while mounting /lscratch: mount source /lscratch doesn't exist.

**Comment by jonahcullen** [comment]
Can you copy/paste the command that resulted in this error?

**Comment by sachin11645** [comment]
I have fixed the error now. 

I executed
$ singularity exec /path/wags.sif tree /path/ -L 2. How can I see adjacent reference genome for dogs

**Comment by jonahcullen** [comment]
Apologies I didn't see your response. Yes if you run that command as above with `/home/refgen/ -L 2` you should be able to see there are 3 canine references: _canfam3_, _canfam4_, and _UU_Cfam_GSD_1.0_ROSY_. That last one if really _canfam4_ with the Y chromosome from the Rosalind Institute.

**Comment by sachin11645** [comment]
0 directories, 0 files

It says zero directory and files.

**Comment by sachin11645** [comment]
Thank you sir for the information. I've now identified three canine reference genomes. If I were to generate a new canine reference genome, are there specific steps or considerations I should be aware of in relation to the WAGS pipeline? Additionally, I could use guidance in constructing custom workflows based on these tutorials, especially for the FASTQ to GVCF to VCF process, since I'm relatively unfamiliar with this methodology.

**Comment by jonahcullen** [comment]
Yes there is a script to prepare genome files for wags (see `prep_custom_ref.py` in the repository main page).

As far as guidance on producing your own workflows, I would suggest checking out the snakemake [website](https://snakemake.readthedocs.io/en/stable/tutorial/tutorial.html) or the Software Carpentries has a nice [introduction](https://carpentries-incubator.github.io/workflows-snakemake/).

**Comment by sachin11645** [comment]
Thank you very much sir.
