### ISSUE TITLE
Using prep_custom_ref.py

### ISSUE THREAD

**Issue by sachin11645** [jonahcullen/wags#34]
Hi Dr. Cullen

I have downloaded the SRA files of dogs from NCBI and converted them into FASTQ format using the SRA toolkit in the cluster. I am trying to use WAGS to align them to CanFam4 to get output in gvcf, which I will later combine into gvcf files. I am going through the paper on WAGS as well as Git Hub. I am trying to use prep_custom_ref.py to convert FASTQ to BAM. Can “prep_custom_ref.py” work for this? 

Best,
Sachin

**Comment by jonahcullen** [comment]
So `prep_custom-ref.py` would be used if you wanted to use a difference canine reference that is not in the container. If you want to process FASTQ to BAM and to GVCF, you'll want to checkout `prep_subs.py`. Try running `python prep_subs.py --help` to see the available options (for example `--ref` can be used to specify `canfam4` or `UU_Cfam_GSD_1.0_ROSY` which is canfam4 + chrY.

**Comment by sachin11645** [comment]
Thank you Dr.Cullen
