### ISSUE TITLE
Setting variables for prep_subs.py

### ISSUE THREAD

**Issue by sachin11645** [jonahcullen/wags#36]
Hi Dr. Cullen,

I have a question regarding running [prep_subs.py](https://github.com/jonahcullen/wags/blob/main/wags/prep_subs.py). 
How can I to set the values for these variables:
•	REF_GENOME (canfam4)
•	RESULTS

I have figured out how to set other variables like SNAKEMAKE_ENV, PAR1,PAR2, HPC_ACCOUNT MINIO_ALIAS, but I have an issue setting up the above two. I think the reference genome needs singularity execution

Best Regards,
Sachin

**Comment by jonahcullen** [comment]
Hello, I'm not sure of which arguments you are referring. If you are planning to use canfam4, you can set that with `--ref canfam4` - for genomes included in the container, `--ref-dir` is not needed. Which argument do you mean for RESULTS?

**Comment by sachin11645** [comment]
Thank you for your reply Dr. Culllen,

Actually I am trying the following script to run in my cluster:

python /scratch/ss11645/LC/SRA/prefetchData/sra/wags/wags/prep_subs.py \
    --meta /scratch/ss11645/LC/SRA/prefetchData/sra/input.csv \
    --fastqs /scratch/ss11645/LC/SRA/prefetchData/sra \
    --ref REF_GENOME \         
    --out /scratch/ss11645/LC/SRA/prefetchData/sra/out \                   
    --bucket RESULTS \                  
    --snake-env SNAKEMAKE_ENV \
    --partition PAR1,PAR2 \
    --email ss11645@xyz.edu \
    --account HPC_ACCOUNT \
    --remote S3 \
    --alias MINIO_ALIAS.


I am looking for results that denotes the bucket.

Best Regards,
Sachin

**Comment by sachin11645** [comment]
Hi Dr. Cullen,

I have a question regarding the bucket in prep_subs.py. The documentation says that the --bucket is the name of the per-sample output directory nested within --out and must be an available S3 bucket if using --remote S3. How can I set this bucket to run the script in the cluster?

Best Regards,
Sachin

**Comment by jonahcullen** [comment]
Perhaps naming it `--bucket` was a bit too skewed toward using S3. The argument `--bucket` can be any name you choose if you are not planning on saving the outputs to secondary storage accessed via Amazon S3. The argument just defines the "results" directory. I would try to run `prep_subs.py` using `--remote local` (another argument I should rename!) with `--bucket RESULTS` so you can see how that applies.

**Comment by sachin11645** [comment]
Thank you Dr. Cullen
