### ISSUE TITLE
CanFam4 Dictionary Missing?

### ISSUE THREAD

**Issue by epersoon** [jonahcullen/wags#39]
I am trying to run the oneWAGS pipeline with a group of dogs and encountered an error. It looks like the reference dictionary for canfam4 cannot be found by the code. 
`FileNotFoundError in file /scratch.global/epersoon/wdp_wags/standard_poodle/102/canfam4/src/utils.py, line 18:
[Errno 2] No such file or directory: 'canFam4.dict'
  File "/scratch.global/epersoon/wdp_wags/standard_poodle/102/canfam4/one_wag.smk", line 34, in <module>
  File "/scratch.global/epersoon/wdp_wags/standard_poodle/102/canfam4/src/utils.py", line 18, in sequence_grouping
`
I downloaded the most recent version of the pipeline and container this morning. :)

**Comment by epersoon** [comment]
It was a dry run. I looked in the config file and the pathway to the dictionary does not match the pathways to the other files in the container. 
`python prep_subs.py -m ~/fastq_dogids/fastq_dogid_1.csv -f /scratch.global/epersoon/wdpfastqs/ -r canfam4 -o /scratch.global/epersoon/wdp_wags -b s3/wdpwags -s snakemake -p msismall,msilarge -e perso208@umn.edu -a mccuem --remote S3`

**Comment by jonahcullen** [comment]
Before the dry run will work, you'll need to run that first bit of code that starts with `singularity exec --bind ...`

**Comment by jonahcullen** [comment]
Let me know if you are seeing having issues with this!
