### ISSUE TITLE
Error when running one_wag.slurm

### ISSUE THREAD

**Issue by gwigley409** [jonahcullen/wags#40]
Hello! I am fairly new to this so I apologize if this is an easy fix. I am getting an error when running one_wag.slurm script:

FileNotFoundError in file /scratch/negishi/gwigley/WAGS_TEST/output/BassetHound/13641/UU_Cfam_GSD_1.0_ROSY/src/utils.py, line 69:
[Errno 2] No such file or directory: ' RESULTS /bed_group / bed_group_ 0000 .bed '
  File "/scratch/negishi/gwigley/WAGS_TEST/output/BassetHound/13641/UU_Cfam_GSD_1.0_ROSY/one_wag.smk", line 24, in <module>
  File "/scratch/negishi/gwigley/WAGS_TEST/output/BassetHound/13641/UU_Cfam_GSD_1.0_ROSY/src/utils.py", line 69, in sequence_grouping

It also appears to be generating two RESULTS directories, one that contains spaces in the name (and has seq_group as the subdirectory) and one that does not (has bed_group as the subdirectory). 

gwigley@login04.negishi:[UU_Cfam_GSD_1.0_ROSY] $ ls -l -a
total 384
drwxr-xr-x 9 gwigley student   4096 Jan 24 11:12  .
drwxr-xr-x 3 gwigley student   4096 Jan 24 11:11  ..
-rw-r--r-- 1 gwigley student    963 Jan 24 11:11  BassetHound_13641.one_wag.slurm
-rw-r--r-- 1 gwigley student    380 Jan 24 11:11  input.tsv
-rw-r--r-- 1 gwigley student   1798 Jan 24 11:11  one_wag.smk
drwxr-xr-x 3 gwigley student   4096 Jan 24 11:12 ' RESULTS '
drwxr-xr-x 3 gwigley student   4096 Jan 24 11:12  RESULTS
drwxr-xr-x 2 gwigley student   4096 Jan 18 10:57  rules
drwxr-xr-x 2 gwigley student   4096 Jan 24 11:11  slurm.go_wags
drwxr-xr-x 2 gwigley student   4096 Jan 24 11:12  slurm_logs
drwxr-xr-x 3 gwigley student   4096 Jan 24 11:12  .snakemake
drwxr-xr-x 2 gwigley student   4096 Jan 18 10:57  src
-rw-r--r-- 1 gwigley student    655 Jan 24 11:11  UU_Cfam_GSD_1.0_ROSY_config.yaml
-rw-r--r-- 1 gwigley student 337448 Jan 24 11:12  UU_Cfam_GSD_1.0_ROSY.dict

I can't seem to find a solution to this error. I appreciate all of your help!

**Comment by jonahcullen** [comment]
No problem at all! Can you send me the `prep_subs.py` command you used?

**Comment by gwigley409** [comment]
python /scratch/negishi/gwigley/wags/wags/prep_subs.py \
--meta /scratch/negishi/gwigley/WAGS_TEST/13641_input.csv \
--fastqs /scratch/negishi/gwigley/WAGS_TEST \
--ref UU_Cfam_GSD_1.0_ROSY \
--out /scratch/negishi/gwigley/WAGS_TEST/output \
--bucket RESULTS \
--snake-env snakemakeV7.24.0 \
--partition a \
--email gwigley@purdue.edu \
--account kje0003 \
--remote local \
--sif /scratch/negishi/gwigley/wags.sif

**Comment by aletko** [comment]
Hello! Just to add I have also seen this problem of creating directory name with spaces, when using python version 3.12. So far, I “solved” it by using python 3.11. 
Maybe that helps with figuring it out. :-)

**Comment by gwigley409** [comment]
Thank you! Switching to python 3.11 seemed to "fix" the problem.

**Comment by jonahcullen** [comment]
Thanks @aletko ! I will update the install instructions to address this.
